universe                = docker
docker_image            = pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel

executable              = run_densenet.sh

output                  = runlogs/densenet_ce.$(ClusterId).$(ProcId).out
error                   = runlogs/densenet_ce.$(ClusterId).$(ProcId).err
log                     = runlogs/densenet_ce.$(ClusterId).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

request_GPUs            = 1
request_CPUs            = 4
request_memory          = 16G

requirements            = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted     = true
+WantScratchMounted     = true

queue 1