universe                = docker
docker_image            = pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel

executable              = code/gpu_test.py

output                  = runlogs/gpu_test.$(ClusterId).$(ProcId).out
error                   = runlogs/gpu_test.$(ClusterId).$(ProcId).err
log                     = runlogs/gpu_test.$(ClusterId).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

request_GPUs            = 1
request_CPUs            = 1
request_memory          = 2G

requirements            = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted     = true
+WantScratchMounted     = true

queue 1
